### ISSUE TITLE
The widget label should use the title or heading property of the widget instead of the class name!

### ISSUE THREAD

**Issue by StaffCollab** [kenepa/multi-widget#12]
It currently uses the class name only...
In a lot of cases, that's not the desired behavior.

**Comment by Jehizkia** [comment]
Nice suggestion! If you can whip up a PR, I'll take a look at it.

**Comment by 33Piter** [comment]
You can define a custom display name of the widget by adding a `getDisplayName()` method to it:

```
public function getDisplayName(): ?string
{
    return 'My Custom Widget Name';
}
```
